#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: /Users/yangqiang/Desktop/idea/logtest/spring.log
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/eshop?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  jpa:
    show-sql: true

server:
#  context-path: /service/
  port: 8081
mybatis:
  type-aliases-package: com.test.eshop.inventory.mapper
  mapper-locations: classpath*:/mapper/*.xml
eureka:
  instance:
    hostname: localhost1
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/



